Disable local forgejo-runner and forgejo-dind

diff --git a/forgejo.yml b/forgejo.yml
--- a/forgejo.yml
+++ b/forgejo.yml
@@ -6,8 +6,8 @@ networks:
 volumes:
   forgejo-data:
   forgejo-database-data:
-  forgejo-runner-data:
-  dind-certs:
+  # forgejo-runner-data:
+  # dind-certs:
 
 services:
   forgejo-anubis:
@@ -27,12 +27,13 @@ services:
   forgejo:
     # note: to automatically create a new user, add to the executed command, before sleep infinity:
     # forgejo admin user create --admin --username user --password password --email email@domain.tld || true ;
+    # note: add runner registration just before admin auth if a local runner is required:
+    # forgejo forgejo-cli actions register --secret ${FORGEJO_RUNNER_SECRET} --name box || true ;
     image: codeberg.org/forgejo/forgejo:15.0.3-rootless
     command: >-
       /bin/sh -c '
       gitea --config /var/lib/gitea/custom/conf/app.ini &
       sleep 10 ;
-      forgejo forgejo-cli actions register --secret ${FORGEJO_RUNNER_SECRET} --name box || true ;
       forgejo admin auth add-oauth --provider=openidConnect --name=Authelia \
         --key=${AUTH_FORGEJO_CLIENT_ID} --secret=${AUTH_FORGEJO_CLIENT_SECRET} \
         --auto-discover-url=https://auth.${PROXY_PUBLIC_DOMAIN}/.well-known/openid-configuration \
@@ -134,58 +135,58 @@ services:
     volumes:
       - forgejo-database-data:/var/lib/postgresql/data
 
-  forgejo-dind:
-    image: docker.io/docker:29.3.1-dind
-    hostname: docker # must be `docker` or `localhost`, TLS certificates are only valid for these
-    privileged: true
-    environment:
-      - DOCKER_TLS_CERTDIR=/certs
-    expose:
-      - 2376 # tcp
-    extends:
-      file: common.yml
-      service: log-to-json
-    healthcheck:
-      test: ["CMD", "docker", "info"]
-      interval: 10s
-      timeout: 10s
-      retries: 5
-      start_period: 30s
-    networks:
-      - forgejo
-    restart: unless-stopped
-    volumes:
-      - dind-certs:/certs
-
-  forgejo-runner:
-    image: code.forgejo.org/forgejo/runner:12.12.0
-    command: >-
-      /bin/sh -c '
-      while : ; do
-        forgejo-runner create-runner-file --connect --instance http://forgejo:3000 --name box --secret ${FORGEJO_RUNNER_SECRET} --config /runner.yml && break ;
-        sleep 5 ;
-      done ;
-      while : ;
-        do test -w .runner && forgejo-runner --config /runner.yml daemon ;
-        sleep 5 ;
-      done ;
-      '
-    depends_on:
-      forgejo:
-        condition: service_healthy
-      forgejo-dind:
-        condition: service_healthy
-    environment:
-      - DOCKER_HOST=tcp://docker:2376
-      - DOCKER_CERT_PATH=/certs/client
-      - DOCKER_TLS_VERIFY=1
-    extends:
-      file: common.yml
-      service: log-to-json
-    networks:
-      - forgejo
-    restart: unless-stopped
-    volumes:
-      - forgejo-runner-data:/data
-      - dind-certs:/certs:ro
-      - ./forgejo/runner.yml:/runner.yml:ro
+  # forgejo-dind:
+  #   image: docker.io/docker:29.3.1-dind
+  #   hostname: docker # must be `docker` or `localhost`, TLS certificates are only valid for these
+  #   privileged: true
+  #   environment:
+  #     - DOCKER_TLS_CERTDIR=/certs
+  #   expose:
+  #     - 2376 # tcp
+  #   extends:
+  #     file: common.yml
+  #     service: log-to-json
+  #   healthcheck:
+  #     test: ["CMD", "docker", "info"]
+  #     interval: 10s
+  #     timeout: 10s
+  #     retries: 5
+  #     start_period: 30s
+  #   networks:
+  #     - forgejo
+  #   restart: unless-stopped
+  #   volumes:
+  #     - dind-certs:/certs
+  #
+  # forgejo-runner:
+  #   image: code.forgejo.org/forgejo/runner:12.12.0
+  #   command: >-
+  #     /bin/sh -c '
+  #     while : ; do
+  #       forgejo-runner create-runner-file --connect --instance http://forgejo:3000 --name box --secret ${FORGEJO_RUNNER_SECRET} --config /runner.yml && break ;
+  #       sleep 5 ;
+  #     done ;
+  #     while : ;
+  #       do test -w .runner && forgejo-runner --config /runner.yml daemon ;
+  #       sleep 5 ;
+  #     done ;
+  #     '
+  #   depends_on:
+  #     forgejo:
+  #       condition: service_healthy
+  #     forgejo-dind:
+  #       condition: service_healthy
+  #   environment:
+  #     - DOCKER_HOST=tcp://docker:2376
+  #     - DOCKER_CERT_PATH=/certs/client
+  #     - DOCKER_TLS_VERIFY=1
+  #   extends:
+  #     file: common.yml
+  #     service: log-to-json
+  #   networks:
+  #     - forgejo
+  #   restart: unless-stopped
+  #   volumes:
+  #     - forgejo-runner-data:/data
+  #     - dind-certs:/certs:ro
+  #     - ./forgejo/runner.yml:/runner.yml:ro
